version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '3001:8088'
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3002:3000'
  # environment:
  #   - CHOKIDAR_USEPOLLING=true

  xero-mock-api:
    image: jaypeng2015/show-me-the-money
    ports:
      - '3000:3000'
